
#通用配置
#短信发送配置
sms:
  config:
    account: jiekou-clcs-03
    pswd: BHM465bjhs
    target-url: http://sapi.253.com/msg/HttpBatchSendSM?
    msg: 您好，您的验证码是：CODE
    need-status: true
    ext-no: 999
#定时任务
task:
  crontab:
    #定时每点的第5分钟触发
    every-hour-five-minute: "* 5 * * * ?"
    #定时任务每天凌晨12点半触发
    every-day-half-past-twelve: "0 30 0  * * ?"
#数据库通用配置
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
        use_sql_comments: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    max-active: 200
    max-idle: 10
    min-idle: 10
    initial-size: 10
    validation-query:  SELECT 'X'
    test-on-borrow: false
    test-on-return: false
    test-while-idle: true
    time-between-eviction-runs-millis: 3000
    min-evictable-idle-time-millis: 300000
    max-wait: 60000
    jmx-enabled: false
  aop:
    proxy-target-class: true

#负载均衡配置
ribbon:
  maxAutoRetries: 1
  ReadTimeout: 60000
  ConnectTimeout: 6000
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 60000
      fallback:
        isolation:
          semaphore:
            maxConcurrentRequests: 200
  threadpool:
    default:
      coreSize: 200
      maxQueueSize: 200
      queueSizeRejectionThreshold: 200
#阿里云OSS服务
aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI3xfZA5pukD7s
    access-key-secret: EhnqXyTr5TUEQ68MGroFZq2nCwnmdd
    bucket-name: gt-jizhi-dev
activemq:
  queue:
    real-time-queue: REAL_TIME
    delayed-queue: DELAYED
    delay-time: 300000
thread:
  pool:
    queue-capacity: 200
    core-pool-size: 5
    max-pool-size: 20
    keep-alive-seconds: 300000


---
#native
#商户充值
merchant:
  app-id: wxcf6f481cd6337688
  asign-key: 7b7256e181774b25858898e3b008e19b
  mch-id: 1401963702
  spbill-create-ip: 119.57.161.138
  notify-url: http://dev.tracing.grouptactic.com/jizhi/payment
#第三方平台信息
component:
  base-url: http://dev.jizhi.grouptactic.com/jizhi/
  app-id: wx03933cca44abcc4e
  app-secrect: 8d585cda665013f9d113b2383f786b0e
  token: GroupTacticJizhi4DEV
  encoding-aes-key: GroupTacticJizhi4DEViTZ7EsfiLEilA9hd4YjpsWn
  oauth-redirect-url: http://139.129.207.221/jizhi/channels/authorized
  qr-code-expire-time: 600
spring:
  profiles: native
  activemq:
    broker-url: tcp://139.129.207.221:61616
    user: system
    password: manager
  redis:
#    host: 127.0.0.1
    host: 139.129.207.221
    port: 6380
    password: grouptactic
  data:
    mongodb:
      uri: mongodb://139.129.207.221:27017/jizhi_dev
  datasource:
    url: jdbc:mysql://rm-2ze2ckz2q8r3sec86.mysql.rds.aliyuncs.com:3306/group_tactic_jizhi_dev?characterEncoding=utf-8
    username: jizhiadmin
    password: GroupTactic.jizhi.123
youzan:
  redirectUrl: http://dev.jizhi.grouptactic.com/jizhi/youzan/callback

---
#sit
#第三方平台信息
component:
  base-url: http://dev.jizhi.grouptactic.com/jizhi/
  app-id: wx03933cca44abcc4e
  app-secrect: 8d585cda665013f9d113b2383f786b0e
  token: GroupTacticJizhi4DEV
  encoding-aes-key: GroupTacticJizhi4DEViTZ7EsfiLEilA9hd4YjpsWn
  oauth-redirect-url: http://dev.jizhi.grouptactic.com/jizhi/channels/authorized
  qr-code-expire-time: 600
#商户充值
merchant:
  app-id: wxcf6f481cd6337688
  asign-key: 7b7256e181774b25858898e3b008e19b
  mch-id: 1401963702
  spbill-create-ip: 139.129.207.221
  notify-url: http://dev.jizhi.grouptactic.com/jizhi/payment
spring:
  profiles: sit
  activemq:
    broker-url: tcp://139.129.207.221:61616
    user: system
    password: manager
  redis:
    host: 139.129.207.221
    port: 6380
    password: grouptactic
  data:
    mongodb:
      uri: mongodb://jizhiadmin:jizhiadmin123@dds-m5e658af05eaa5b41.mongodb.rds.aliyuncs.com:3717,dds-m5e658af05eaa5b42.mongodb.rds.aliyuncs.com:3717/jizhi_dev?replicaSet=mgset-1839551
  datasource:
    url: jdbc:mysql://rm-2ze2ckz2q8r3sec86.mysql.rds.aliyuncs.com:3306/group_tactic_jizhi_dev?characterEncoding=utf-8
    username: jizhiadmin
    password: GroupTactic.jizhi.123
youzan:
  redirectUrl: http://dev.jizhi.grouptactic.com/jizhi/youzan/callback